# build.yaml
targets:
  $default:
    builders:
      source_gen:combining_builder:
        generate_for:
          - "lib/**/[!objectbox]**.dart"
          - "lib/providers/**.dart"
          - "lib/models/sessions.dart"
          - "lib/models/session_sql_result.dart"