name: db_driver
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  json_annotation: ^4.9.0
  # path: ^1.8.0
  mysql:
    path: impl/mysql/
  pg:
    path: impl/pg/
  sql_parser:
    path: ../sql_parser/

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.9
