// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_sync_flutter_libs/objectbox_sync_flutter_libs.dart';

import '../repositories/instances.dart';
import '../repositories/sessions.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 7771770525022327494),
    name: 'InstanceModel',
    lastPropertyId: const obx_int.IdUid(13, 9103170210888742968),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4402971908614233426),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2557526817954957013),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1533736204012627434),
        name: 'host',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8657086904403898878),
        name: 'port',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7449270155428902133),
        name: 'user',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7099609988433500239),
        name: 'password',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 8699536140751700883),
        name: 'desc',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 6180271050918009273),
        name: 'initQuerys',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7938579034731173175),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 5382849423225960488),
        name: 'latestOpenAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 451105937567216074),
        name: 'stDbType',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 3794023625132426927),
        name: 'stCustom',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 9103170210888742968),
        name: 'stActiveSchemas',
        type: 30,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 954363933915371259),
    name: 'SessionStorage',
    lastPropertyId: const obx_int.IdUid(4, 2680331308371878199),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 517178709276681653),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4854003834765344230),
        name: 'instanceId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(2, 3493315780447542151),
        relationTarget: 'InstanceModel',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4040787782661306959),
        name: 'text',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2680331308371878199),
        name: 'currentSchema',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(3, 954363933915371259),
    lastIndexId: const obx_int.IdUid(2, 3493315780447542151),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [4777369979113529251],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      6339393024853594017,
      2012876000864412152,
      3055836543278863247,
      2576353234273015585,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    InstanceModel: obx_int.EntityDefinition<InstanceModel>(
      model: _entities[0],
      toOneRelations: (InstanceModel object) => [],
      toManyRelations: (InstanceModel object) => {},
      getId: (InstanceModel object) => object.id,
      setId: (InstanceModel object, int id) {
        object.id = id;
      },
      objectToFB: (InstanceModel object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final hostOffset = fbb.writeString(object.host);
        final userOffset = fbb.writeString(object.user);
        final passwordOffset = fbb.writeString(object.password);
        final descOffset = fbb.writeString(object.desc);
        final initQuerysOffset = fbb.writeList(
          object.initQuerys.map(fbb.writeString).toList(growable: false),
        );
        final stCustomOffset = fbb.writeString(object.stCustom);
        final stActiveSchemasOffset = fbb.writeList(
          object.stActiveSchemas.map(fbb.writeString).toList(growable: false),
        );
        fbb.startTable(14);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, hostOffset);
        fbb.addInt64(3, object.port);
        fbb.addOffset(4, userOffset);
        fbb.addOffset(5, passwordOffset);
        fbb.addOffset(6, descOffset);
        fbb.addOffset(7, initQuerysOffset);
        fbb.addInt64(8, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(9, object.latestOpenAt?.millisecondsSinceEpoch);
        fbb.addInt64(10, object.stDbType);
        fbb.addOffset(11, stCustomOffset);
        fbb.addOffset(12, stActiveSchemasOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final latestOpenAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          22,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final stDbTypeParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          24,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final hostParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final portParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          10,
        );
        final userParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final passwordParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final descParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final stCustomParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 26, '');
        final initQuerysParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 18, []);
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0),
        );
        final latestOpenAtParam =
            latestOpenAtValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(latestOpenAtValue);
        final object = InstanceModel(
            id: idParam,
            stDbType: stDbTypeParam,
            name: nameParam,
            host: hostParam,
            port: portParam,
            user: userParam,
            password: passwordParam,
            desc: descParam,
            stCustom: stCustomParam,
            initQuerys: initQuerysParam,
            createdAt: createdAtParam,
            latestOpenAt: latestOpenAtParam,
          )
          ..stActiveSchemas = const fb.ListReader<String>(
            fb.StringReader(asciiOptimization: true),
            lazy: false,
          ).vTableGet(buffer, rootOffset, 28, []);

        return object;
      },
    ),
    SessionStorage: obx_int.EntityDefinition<SessionStorage>(
      model: _entities[1],
      toOneRelations: (SessionStorage object) => [object.instance],
      toManyRelations: (SessionStorage object) => {},
      getId: (SessionStorage object) => object.id,
      setId: (SessionStorage object, int id) {
        object.id = id;
      },
      objectToFB: (SessionStorage object, fb.Builder fbb) {
        final textOffset =
            object.text == null ? null : fbb.writeString(object.text!);
        final currentSchemaOffset =
            object.currentSchema == null
                ? null
                : fbb.writeString(object.currentSchema!);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.instance.targetId);
        fbb.addOffset(2, textOffset);
        fbb.addOffset(3, currentSchemaOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final textParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final currentSchemaParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final object = SessionStorage(
          id: idParam,
          text: textParam,
          currentSchema: currentSchemaParam,
        );
        object.instance.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        object.instance.attach(store);
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [InstanceModel] entity fields to define ObjectBox queries.
class InstanceModel_ {
  /// See [InstanceModel.id].
  static final id = obx.QueryIntegerProperty<InstanceModel>(
    _entities[0].properties[0],
  );

  /// See [InstanceModel.name].
  static final name = obx.QueryStringProperty<InstanceModel>(
    _entities[0].properties[1],
  );

  /// See [InstanceModel.host].
  static final host = obx.QueryStringProperty<InstanceModel>(
    _entities[0].properties[2],
  );

  /// See [InstanceModel.port].
  static final port = obx.QueryIntegerProperty<InstanceModel>(
    _entities[0].properties[3],
  );

  /// See [InstanceModel.user].
  static final user = obx.QueryStringProperty<InstanceModel>(
    _entities[0].properties[4],
  );

  /// See [InstanceModel.password].
  static final password = obx.QueryStringProperty<InstanceModel>(
    _entities[0].properties[5],
  );

  /// See [InstanceModel.desc].
  static final desc = obx.QueryStringProperty<InstanceModel>(
    _entities[0].properties[6],
  );

  /// See [InstanceModel.initQuerys].
  static final initQuerys = obx.QueryStringVectorProperty<InstanceModel>(
    _entities[0].properties[7],
  );

  /// See [InstanceModel.createdAt].
  static final createdAt = obx.QueryDateProperty<InstanceModel>(
    _entities[0].properties[8],
  );

  /// See [InstanceModel.latestOpenAt].
  static final latestOpenAt = obx.QueryDateProperty<InstanceModel>(
    _entities[0].properties[9],
  );

  /// See [InstanceModel.stDbType].
  static final stDbType = obx.QueryIntegerProperty<InstanceModel>(
    _entities[0].properties[10],
  );

  /// See [InstanceModel.stCustom].
  static final stCustom = obx.QueryStringProperty<InstanceModel>(
    _entities[0].properties[11],
  );

  /// See [InstanceModel.stActiveSchemas].
  static final stActiveSchemas = obx.QueryStringVectorProperty<InstanceModel>(
    _entities[0].properties[12],
  );
}

/// [SessionStorage] entity fields to define ObjectBox queries.
class SessionStorage_ {
  /// See [SessionStorage.id].
  static final id = obx.QueryIntegerProperty<SessionStorage>(
    _entities[1].properties[0],
  );

  /// See [SessionStorage.instance].
  static final instance = obx.QueryRelationToOne<SessionStorage, InstanceModel>(
    _entities[1].properties[1],
  );

  /// See [SessionStorage.text].
  static final text = obx.QueryStringProperty<SessionStorage>(
    _entities[1].properties[2],
  );

  /// See [SessionStorage.currentSchema].
  static final currentSchema = obx.QueryStringProperty<SessionStorage>(
    _entities[1].properties[3],
  );
}
