builders:
  # name of the builder
  property_sum:
    import: "package:sql_parser/builder.dart"
    builder_factories: ["sumBuilder"]
    build_extensions: {".dart": ["sum.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]

targets:
  $default:
    builders:
      # Configure the builder `pkg_name|builder_name`
      # In this case, the member_count builder defined in `../example`
      sql_parser:property_sum:
        # Only run this builder on the specified input.
        generate_for:
          - lib/src/build/example.dart