import 'dart:io';

import 'package:sql_complete/training.dart';

/// 包内预置权重生成文件（JSON 常量；loader 见 `lib/src/checkpoint.dart`）。
const defaultBundledCheckpointDataPath = 'lib/src/bundled_checkpoint_data.dart';

/// 将 [ckpt] 截断后写入 `bundled_checkpoint_data.dart`。
///
/// 返回写入的文件；JSON 含 `'''` 时抛错（无法放进 raw 三引号）。
Future<File> exportBundledCheckpointData(
  Checkpoint ckpt, {
  String path = defaultBundledCheckpointDataPath,
  int fractionDigits = 6,
}) async {
  final json = ckpt.toCompactJson(fractionDigits: fractionDigits);
  if (json.contains("'''")) {
    throw StateError(
      "exported JSON contains ''', cannot embed as raw string",
    );
  }

  final dart = StringBuffer()
    ..writeln(
      '// GENERATED by tool/export.dart / train --export — do not edit.',
    )
    ..writeln('// ignore_for_file: lines_longer_than_80_chars')
    ..writeln()
    ..writeln('/// Compact checkpoint JSON embedded for runtime load.')
    ..writeln("const bundledCheckpointJson = r'''")
    ..write(json)
    ..writeln("''';")
    ..writeln();

  final file = File(path);
  await file.parent.create(recursive: true);
  await file.writeAsString(dart.toString());
  return file;
}

/// 把已有 checkpoint 写入 `bundled_checkpoint_data.dart`。
///
/// ```bash
/// dart run tool/train.dart --full --epochs=3
/// dart run tool/export.dart   # 仅重嵌时用；--full 训练默认已 export
/// ```
Future<void> main(List<String> args) async {
  final src = args.isNotEmpty
      ? args[0]
      : _firstExisting([
          'out/trainset_model.checkpoint.json',
          'pkg/sql_complete/out/trainset_model.checkpoint.json',
        ]);
  final outPath = args.length > 1
      ? args[1]
      : _firstExisting([
          defaultBundledCheckpointDataPath,
          'pkg/sql_complete/$defaultBundledCheckpointDataPath',
        ]) ??
          defaultBundledCheckpointDataPath;

  if (src == null) {
    stderr.writeln(
      'checkpoint not found. Train first:\n'
      '  dart run tool/train.dart --full --epochs=3',
    );
    exit(1);
  }

  stdout.writeln('loading $src ...');
  final ckpt = await loadCheckpoint(src);
  stdout.writeln(
    'vocab=${ckpt.vocab.size} targets=${ckpt.targetIds.length} '
    'layers=${ckpt.model.config.numLayers} maxPosLen=${ckpt.model.config.maxPosLen}',
  );

  final file = await exportBundledCheckpointData(ckpt, path: outPath);
  final bytes = await file.length();
  stdout.writeln('exported -> ${file.path} ($bytes bytes)');
}

String? _firstExisting(List<String> paths) {
  for (final p in paths) {
    if (File(p).existsSync() || Directory(p).existsSync()) return p;
  }
  return null;
}
